/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m3agit;

import java.time.LocalDate;

/**
 *
 * @author Joseline
 */
public class Reloj1 extends javax.swing.JFrame {

    /**
     * Creates new form Reloj1
     */
    public Reloj1() {
        initComponents();
        Proceso1 r = new Proceso1(this.lbReloj);
        Progress p = new Progress(this.barra);
        p.start();
        try {
            this.setVisible(true);
            barra.setVisible(true);
            p.join();
            
        
        } catch (InterruptedException ex) {
            System.out.println("ERROR");
        }
        r.start();
        LocalDate fech = LocalDate.now();
        lbfecha.setText(String.valueOf(fech));
        
        ///metodoss yield//
        Proceso2 hilo1 = new Proceso2(lab1);
        Proceso3 hilo2 = new Proceso3(lab2);
        
        hilo1.start();
        hilo2.start();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        barra = new javax.swing.JProgressBar();
        lbfecha = new javax.swing.JLabel();
        lbReloj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ed = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 210, -1));

        lbfecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbfecha.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(lbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 140, 20));

        lbReloj.setFont(new java.awt.Font("Agency FB", 1, 50)); // NOI18N
        lbReloj.setForeground(new java.awt.Color(0, 153, 0));
        lbReloj.setText("jLabel1");
        lbReloj.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 200, 115));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reloj.JPG"))); // NOI18N
        jLabel1.setText("aaa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 360));

        ed.setText("jLabel2");
        getContentPane().add(ed, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        lab1.setText("jLabel2");
        getContentPane().add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        lab2.setText("jLabel2");
        getContentPane().add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reloj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reloj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reloj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reloj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reloj1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel ed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lbReloj;
    private javax.swing.JLabel lbfecha;
    // End of variables declaration//GEN-END:variables
}
